### ISSUE TITLE
[Chore] 개발 환경 구축 : 스토리북을 활용한 CI 환경 구축

### ISSUE THREAD

**Issue by yonghyeun** [dogandme/frontend#4]
### 목적

스토리북을 활용한 CI 환경을 구축하여 테스트 주도적으로 개발 하기 위함입니다. 

- 설치 
- [x] `storybook`
- [x] `@storybook/test-runner` : 개발 시 `CLI` 환경에서 스토리북의 테스트를 가능하게 하기 위함입니다. `npm run test-storybook` 커맨드를 이용해 테스트 가능합니다. 
- [x] `chromatic` : cloud-based 서비스로 스토리북을 호스팅 하고 스토리들의 screenshot을 찍어 visual regression test를 가능하게 하는 라이브러리 
  - [x] dotenv-cli : CLI 환경에서 `.env` 파일을 읽을 수 있게 하는 라이브러리  
  - [x] cross-env : OS에 상관 없이 CLI 에서 script syntax 를 지원하는 라이브러리
  - `npx chromatic` 을 통해 스토리북에 존재하는 스토리들을 정적 파일로 생성하고 스크린샷을 캡쳐하고 업로드 합니다. 이 때 이전과 비교하여 변경 사항이 있을 경우 변경 사항을 알립니다.
  - chromatic project token 을 `.env` 파일에 저장하고 `dotenv-cli` 를 활용하여 CLI 환경에서 환경 변수에 접근하도록 합니다.
  ```json
    "chromatic": "dotenv -e .env cross-env CHROMATIC_PROJECT_TOKEN=$CHROMATIC_PROJECT_TOKEN npx chromatic --project-token=$CHROMATIC_PROJECT_TOKEN"
  ```
  - ![image](https://github.com/user-attachments/assets/c0d5e3cf-4518-4098-8374-50695e264a1b)
  - 로컬 환경에서 `npm run chromatic` 으로 빌드한 후 `reviews` 에 들어어가보면 이전 스크린샷과 비교하여 변경 사항을 Accept 할 수 있도록 함 

- Github Action 작성 

chromatic 으로 build 하는 행위를 로컬이 아닌 dev branch로 build 할 때 사용 할 수 있도록 Github Action 추가

```yml
name: "Chromatic"

on:
  pull_request:
    branches:
      - dev

jobs:
  chromatic:
    name: Run Chromatic and Test Storybook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run interaction tests and save output
        id: test-storybook
        run: npm run test-storybook > test-storybook-output.txt
        continue-on-error: true
      - name: Post test results as PR comment
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('test-storybook-output.txt', 'utf8');
            const success = ${{ steps.test-storybook.outcome }} === 'success';
            const comment = success 
              ? `### ✅ Test-Storybook Results - Success\n\`\`\`\n${output}\n\`\`\``
              : `### ❌ Test-Storybook Results - Failed\n\`\`\`\n${output}\n\`\`\``;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment
            });
      - name: Run Chromatic
        if: success() # Only run if the previous step was successful
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
```
